version: 2.1

parameters:
  workingdir:
    type: string
    default: "~/housing-prediction-api"
  node-image-tag:
    type: string
    default: "14"
  python-image-tag:
    type: string
    default: 3.7.3-stretch
  docker-version:
    type: string
    default: 19.03.13

executors:
  docker-executor:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: << pipeline.parameters.workingdir >>

  node-executor:
    docker:
      - image: circleci/node:<< pipeline.parameters.node-image-tag >>
    working_directory: << pipeline.parameters.workingdir >>

  python-executor:
    docker:
      - image: python:<< pipeline.parameters.python-image-tag >>
    working_directory: << pipeline.parameters.workingdir >>

jobs:
  dependencies:
    executor: python-executor
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint

      - save_cache:
          paths:
            - .venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - persist_to_workspace:
          root: .
          paths: .

  lint:
    executor: python-executor
    steps:
      - attach_workspace:
          at:
            .

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            . .venv/bin/activate
            make lint

  build:
    executor: docker-executor
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint

      - save_cache:
          paths:
            - .venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint

workflows:
  version: 2
  test_build_push_tag:
    jobs:
      - dependencies

      - build:
          requires:
            - dependencies

      - build_docker_image:
          requires:
            - build

      - push_latest:
          context: thelusina-context
          requires:
            - build_docker_image

      - publish_release:
          context: thelusina-context
          requires:
            - push_latest
